"""empty message

Revision ID: 068f6e73b17f
Revises: 7be74e2a36d4
Create Date: 2022-01-05 03:36:22.377135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068f6e73b17f'
down_revision = '7be74e2a36d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
